import 'prayer_models.dart';

/// Global verified preset cities for fast selection, offline devotional use, and testing.
const kGlobalPresetCities = <PresetCity>[
  PresetCity(
    id: 'makkah',
    name: 'Makkah al-Mukarramah',
    nameArabic: 'مكة المكرمة',
    nameUrdu: 'مکہ مکرمہ',
    country: 'Saudi Arabia',
    coordinates: PrayerCoordinates(
      latitude: 21.4225,
      longitude: 39.8262,
      cityName: 'Makkah',
      timezoneId: 'Asia/Riyadh',
    ),
    defaultMethod: CalculationMethod.ummAlQura,
    defaultMadhab: AsrMadhab.standard,
  ),
  PresetCity(
    id: 'madinah',
    name: 'Al-Madinah al-Munawwarah',
    nameArabic: 'المدينة المنورة',
    nameUrdu: 'مدینہ منورہ',
    country: 'Saudi Arabia',
    coordinates: PrayerCoordinates(
      latitude: 24.4672,
      longitude: 39.6111,
      cityName: 'Madinah',
      timezoneId: 'Asia/Riyadh',
    ),
    defaultMethod: CalculationMethod.ummAlQura,
    defaultMadhab: AsrMadhab.standard,
  ),
  PresetCity(
    id: 'jerusalem',
    name: 'Al-Quds (Jerusalem)',
    nameArabic: 'القدس الشريف',
    nameUrdu: 'القدس',
    country: 'Palestine',
    coordinates: PrayerCoordinates(
      latitude: 31.7683,
      longitude: 35.2137,
      cityName: 'Jerusalem',
      timezoneId: 'Asia/Jerusalem',
    ),
    defaultMethod: CalculationMethod.mwl,
    defaultMadhab: AsrMadhab.standard,
  ),
  PresetCity(
    id: 'cairo',
    name: 'Cairo',
    nameArabic: 'القاهرة',
    nameUrdu: 'قاہرہ',
    country: 'Egypt',
    coordinates: PrayerCoordinates(
      latitude: 30.0444,
      longitude: 31.2357,
      cityName: 'Cairo',
      timezoneId: 'Africa/Cairo',
    ),
    defaultMethod: CalculationMethod.egyptian,
    defaultMadhab: AsrMadhab.standard,
  ),
  PresetCity(
    id: 'istanbul',
    name: 'Istanbul',
    nameArabic: 'إسطنبول',
    nameUrdu: 'استنبول',
    country: 'Turkey',
    coordinates: PrayerCoordinates(
      latitude: 41.0082,
      longitude: 28.9784,
      cityName: 'Istanbul',
      timezoneId: 'Europe/Istanbul',
    ),
    defaultMethod: CalculationMethod.diyanet,
    defaultMadhab: AsrMadhab.hanafi,
  ),
  PresetCity(
    id: 'karachi',
    name: 'Karachi',
    nameArabic: 'كراتشي',
    nameUrdu: 'کراچی',
    country: 'Pakistan',
    coordinates: PrayerCoordinates(
      latitude: 24.8607,
      longitude: 67.0011,
      cityName: 'Karachi',
      timezoneId: 'Asia/Karachi',
    ),
    defaultMethod: CalculationMethod.karachi,
    defaultMadhab: AsrMadhab.hanafi,
  ),
  PresetCity(
    id: 'hyderabad',
    name: 'Hyderabad',
    nameArabic: 'حيدر آباد',
    nameUrdu: 'حیدرآباد',
    country: 'India',
    coordinates: PrayerCoordinates(
      latitude: 17.3850,
      longitude: 78.4867,
      cityName: 'Hyderabad',
      timezoneId: 'Asia/Kolkata',
    ),
    defaultMethod: CalculationMethod.karachi,
    defaultMadhab: AsrMadhab.hanafi,
  ),
  PresetCity(
    id: 'london',
    name: 'London',
    nameArabic: 'لندن',
    nameUrdu: 'لندن',
    country: 'United Kingdom',
    coordinates: PrayerCoordinates(
      latitude: 51.5074,
      longitude: -0.1278,
      cityName: 'London',
      timezoneId: 'Europe/London',
    ),
    defaultMethod: CalculationMethod.mwl,
    defaultMadhab: AsrMadhab.standard,
  ),
  PresetCity(
    id: 'new_york',
    name: 'New York',
    nameArabic: 'نيويورك',
    nameUrdu: 'نیویارک',
    country: 'United States',
    coordinates: PrayerCoordinates(
      latitude: 40.7128,
      longitude: -74.0060,
      cityName: 'New York',
      timezoneId: 'America/New_York',
    ),
    defaultMethod: CalculationMethod.isna,
    defaultMadhab: AsrMadhab.standard,
  ),
  PresetCity(
    id: 'singapore',
    name: 'Singapore',
    nameArabic: 'سنغافورة',
    nameUrdu: 'سنگاپور',
    country: 'Singapore',
    coordinates: PrayerCoordinates(
      latitude: 1.3521,
      longitude: 103.8198,
      cityName: 'Singapore',
      timezoneId: 'Asia/Singapore',
    ),
    defaultMethod: CalculationMethod.muis,
    defaultMadhab: AsrMadhab.standard,
  ),
  PresetCity(
    id: 'oslo',
    name: 'Oslo',
    nameArabic: 'أوسلو',
    nameUrdu: 'اوسلو',
    country: 'Norway',
    coordinates: PrayerCoordinates(
      latitude: 59.9139,
      longitude: 10.7522,
      cityName: 'Oslo',
      timezoneId: 'Europe/Oslo',
    ),
    defaultMethod: CalculationMethod.mwl,
    defaultMadhab: AsrMadhab.standard,
  ),
  PresetCity(
    id: 'tokyo',
    name: 'Tokyo',
    nameArabic: 'طوكيو',
    nameUrdu: 'ٹوکیو',
    country: 'Japan',
    coordinates: PrayerCoordinates(
      latitude: 35.6762,
      longitude: 139.6503,
      cityName: 'Tokyo',
      timezoneId: 'Asia/Tokyo',
    ),
    defaultMethod: CalculationMethod.mwl,
    defaultMadhab: AsrMadhab.standard,
  ),
  PresetCity(
    id: 'sydney',
    name: 'Sydney',
    nameArabic: 'سيدني',
    nameUrdu: 'سڈنی',
    country: 'Australia',
    coordinates: PrayerCoordinates(
      latitude: -33.8688,
      longitude: 151.2093,
      cityName: 'Sydney',
      timezoneId: 'Australia/Sydney',
    ),
    defaultMethod: CalculationMethod.mwl,
    defaultMadhab: AsrMadhab.standard,
  ),
];
